# Generated by Django 6.0.4 on 2026-05-05 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0012_common_filter_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('listing', 'Listing'), ('user', 'User')], max_length=20)),
                ('reason', models.CharField(choices=[('scam', 'Scam or fraud'), ('inappropriate', 'Inappropriate content'), ('harassment', 'Harassment or abuse'), ('safety', 'Safety concern'), ('wrong_info', 'Wrong or misleading information'), ('spam', 'Spam'), ('other', 'Other')], max_length=40)),
                ('details', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.boatlisting')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['target_type', 'status', '-created_at'], name='report_target_status_idx'), models.Index(fields=['reporter', '-created_at'], name='report_reporter_recent_idx'), models.Index(fields=['listing', '-created_at'], name='report_listing_recent_idx'), models.Index(fields=['reported_user', '-created_at'], name='report_user_recent_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('listing__isnull', False), ('reported_user__isnull', True), ('target_type', 'listing')), models.Q(('listing__isnull', True), ('reported_user__isnull', False), ('target_type', 'user')), _connector='OR'), name='report_exactly_one_matching_target'), models.UniqueConstraint(condition=models.Q(('listing__isnull', False)), fields=('reporter', 'listing'), name='unique_listing_report_per_reporter'), models.UniqueConstraint(condition=models.Q(('reported_user__isnull', False)), fields=('reporter', 'reported_user'), name='unique_user_report_per_reporter')],
            },
        ),
    ]
