# Generated by Django 6.0.4 on 2026-05-05 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_common_filter_indexes'),
        ('listings', '0012_common_filter_indexes'),
        ('reports', '0001_initial'),
        ('reviews', '0006_common_filter_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='report',
            name='report_exactly_one_matching_target',
        ),
        migrations.AddField(
            model_name='report',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chat.message'),
        ),
        migrations.AddField(
            model_name='report',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.review'),
        ),
        migrations.AlterField(
            model_name='report',
            name='target_type',
            field=models.CharField(choices=[('listing', 'Listing'), ('user', 'User'), ('review', 'Review'), ('message', 'Chat message')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['review', '-created_at'], name='report_review_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['message', '-created_at'], name='report_message_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('listing__isnull', False), ('message__isnull', True), ('reported_user__isnull', True), ('review__isnull', True), ('target_type', 'listing')), models.Q(('listing__isnull', True), ('message__isnull', True), ('reported_user__isnull', False), ('review__isnull', True), ('target_type', 'user')), models.Q(('listing__isnull', True), ('message__isnull', True), ('reported_user__isnull', True), ('review__isnull', False), ('target_type', 'review')), models.Q(('listing__isnull', True), ('message__isnull', False), ('reported_user__isnull', True), ('review__isnull', True), ('target_type', 'message')), _connector='OR'), name='report_exactly_one_matching_target'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('review__isnull', False)), fields=('reporter', 'review'), name='unique_review_report_per_reporter'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('message__isnull', False)), fields=('reporter', 'message'), name='unique_message_report_per_reporter'),
        ),
    ]
