# Generated by Django 6.0.3 on 2026-03-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_direct_conversation_uniqueness'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
