# Generated by Django 6.0.3 on 2026-03-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_cover_image_single_source_of_truth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boatlisting',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
