# Generated by Django for TideMate thumbnail support

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_add_more_boat_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatimage',
            name='thumbnail',
            field=models.ImageField(
                blank=True,
                default='',
                upload_to='boats/gallery/thumbnails/',
            ),
            preserve_default=False,
        ),
    ]
