# Generated by Django 6.0.3 on 2026-03-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_favorite_created_at_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
