# Generated by Django 6.0.4 on 2026-05-07 12:16

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_display_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('pending_email'), condition=models.Q(('pending_email__isnull', False), models.Q(('pending_email', ''), _negated=True)), name='users_profile_pending_email_lower_unique'),
        ),
    ]
