# Generated by Django 6.0.4 on 2026-05-01 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_created_e208ff_idx',
            old_name='audit_audit_created_6f3f8e_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_actor_i_fb4253_idx',
            old_name='audit_audit_actor_i_7c54bb_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_action_9e2202_idx',
            old_name='audit_audit_action_ef17ea_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_status_4adadb_idx',
            old_name='audit_audit_status_f10502_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_request_c59dc1_idx',
            old_name='audit_audit_request_44ec59_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_target__59bbff_idx',
            old_name='audit_audit_target__4d2b52_idx',
        ),
    ]
